version: '3'

services:
  app:
    image: v1prod-node
    environment:
      DATABASE: mysql://root:root@db/test
      SMTP_PORT: 1025
      SMTP_HOST: mailhog
    ports:
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: npx mocha --inspect=0.0.0.0:9229 src/**/*.test.js
    links:
      - db
      - mailhog
    depends_on:
      - db
      - mailhog
  db:
    image: mysql:5.7.31
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: '/usr/bin/mysql -u root --password=root -e "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5
    volumes:
      - ./tests/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./tests/docker-mysql-conf.d:/etc/mysql/conf.d
  mycli:
    image: lgatica/mycli
    links:
      - db
    depends_on:
      - db
    environment:
      DATABASE: mysql://root:root@db/test
    entrypoint: /bin/sh
    tty: true
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  redis:
    image: redis:5.0.9-alpine
    ports:
      - 6379:6379
