version: '3'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
        KNOWN_HOST: gitlab.com
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    env_file: .env
    environment:
      NODE_ENV: production
      DATABASE: mysql://root:root@db/development
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7.31
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: '/usr/bin/mysql -u root --password=root -e "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5
  mycli:
    image: lgatica/mycli
    links:
      - db
    depends_on:
      - db
    environment:
      DATABASE: mysql://root:root@db/development
    entrypoint: /bin/sh
    tty: true

volumes:
  mysql-data:
